---
name: Release Extension

"on":
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci
      - name: Package
        run: npx vsce package --no-yarn
      - name: Publish to Marketplace
        run: npx vsce publish -p "${{ secrets.VSCE_PAT }}"
